### ISSUE TITLE
mvp checklist

### ISSUE THREAD

**Issue by michaelpalumbo** [michaelpalumbo/bcc3#1]
- [x] GIVEN I need a new, secure password
- [x] WHEN I click the button to generate a password
- [x] THEN I am presented with a series of prompts for password criteria
- [x] WHEN prompted for password criteria
- [x] THEN I select which criteria to include in the password
- [x] WHEN prompted for the length of the password
- [x] THEN I choose a length of at least 8 characters and no more than 128 characters
- [x] WHEN asked for character types to include in the password
- [x] THEN I confirm whether or not to include lowercase, uppercase, numeric, and/or special characters
- [x] WHEN I answer each prompt
- [ ] THEN my input should be validated and at least one character type should be selected
- [x] WHEN all prompts are answered
- [x] THEN a password is generated that matches the selected criteria
- [x] WHEN the password is generated
- [x] THEN the password is either displayed in an alert or written to the page

- [x] The Challenge should not produce any errors in the console when you inspect it using Chrome DevTools.
- [x] Application deployed at live URL.
- [x] Application loads with no errors.
- [x] Application GitHub URL submitted.
- [x] GitHub repository that contains application code.
- [x] Application user experience is intuitive and easy to navigate.
- [x] Application user interface style is clean and polished.
- [x] Application resembles the mock-up functionality provided in the Challenge instructions.
- [x] Repository has a unique name.
- [x] Repository follows best practices for file structure and naming conventions.
- [x] Repository follows best practices for class/id naming conventions, indentation, quality comments, etc.
- [x] Repository contains multiple descriptive commit messages.
- [x] Repository contains quality README file with description, screenshot, and link to deployed application.
- [x] You are required to submit BOTH of the following for review:
- [x] The URL of the deployed application.
- [x] The URL of the GitHub repository. Give the repository a unique name and include a README describing the project.
